### PR TITLE
Closes #65 Exception in mixin core when checking valid attribute of undefined attribute.

### LINKED ISSUE #65: Exception in mixin core when checking valid attribute of undefined attribute
`ruleHolder` could be null here:
https://github.com/webgme/webgme-engine/blob/master/src/common/core/mixincore.js#L421

### PR DESCRIPTION
**Pull request by kecso**
isValidAttributeValue should throw for checking undefined attribute

### CODE REVIEW

File: src/common/core/core.js [hunk 1]
```diff
@@ -2519,6 +2519,10 @@ define([
             ensureType(name, 'name', 'string');
             ensureValue(value, 'value');
 
+            if ((core.getValidAttributeNames(node) || []).indexOf(name) === -1) {
```
Comment (pmeijer) [inline src/common/core/core.js]: Doesn't `core.getValidAttributeNames(node)` always return an array?
